name: spare_parts
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  firebase_core_platform_interface: 4.5.1
  cloud_firestore: ^3.1.17
  fake_cloud_firestore: ^1.2.2
  provider: ^6.0.3
  mockito: ^5.2.0
  intl: ^0.17.0
  cloud_functions: ^3.3.7
  build_runner: ^2.3.2
  animations: ^2.0.7
  dynamic_color: ^1.6.0
  bluetooth_print: ^4.3.0
  google_sign_in: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

scripts:
  emulate: firebase emulators:start --import ./emulator_data
  build-mocks: flutter pub run build_runner build

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
