import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFFED6819),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFFFDBCC),
  onPrimaryContainer: Color(0xFF351000),
  secondary: Color(0xFF984061),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFFFD9E2),
  onSecondaryContainer: Color(0xFF3E001D),
  tertiary: Color(0xFF2C5DA7),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFD7E2FF),
  onTertiaryContainer: Color(0xFF001B3F),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFEFBFF),
  onBackground: Color(0xFF001849),
  surface: Color(0xFFFEFBFF),
  onSurface: Color(0xFF001849),
  surfaceVariant: Color(0xFFF4DED5),
  onSurfaceVariant: Color(0xFF52443D),
  outline: Color(0xFF85736C),
  onInverseSurface: Color(0xFFEEF0FF),
  inverseSurface: Color(0xFF002B75),
  inversePrimary: Color(0xFFFFB694),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFA14000),
  outlineVariant: Color(0xFFD7C2BA),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFED6819),
  onPrimary: Color(0xFF571F00),
  primaryContainer: Color(0xFF7B2F00),
  onPrimaryContainer: Color(0xFFFFDBCC),
  secondary: Color.fromARGB(255, 234, 144, 92),
  onSecondary: Color(0xFF5E1133),
  secondaryContainer: Color(0xFF7B2949),
  onSecondaryContainer: Color(0xFFFFD9E2),
  tertiary: Color(0xFFABC7FF),
  onTertiary: Color(0xFF002F66),
  tertiaryContainer: Color(0xFF04458E),
  onTertiaryContainer: Color(0xFFD7E2FF),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF101827),
  onBackground: Color(0xFFDBE1FF),
  surface: Color.fromARGB(255, 24, 36, 58),
  onSurface: Color(0xFFDBE1FF),
  surfaceVariant: Color(0xFF52443D),
  onSurfaceVariant: Color(0xFFD7C2BA),
  outline: Color(0xFFA08D85),
  onInverseSurface: Color(0xFF001849),
  inverseSurface: Color(0xFFDBE1FF),
  inversePrimary: Color(0xFFA14000),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFFFB694),
  outlineVariant: Color(0xFF52443D),
  scrim: Color(0xFF000000),
);

ThemeData buildTheme(ColorScheme colorScheme) {
  return ThemeData(
    useMaterial3: true,
    colorScheme: colorScheme,
    buttonTheme: ButtonThemeData(
      alignedDropdown: true,
    ),
    dataTableTheme: DataTableThemeData(
      headingTextStyle: TextStyle(
        color: colorScheme.onSurface,
        fontWeight: FontWeight.bold,
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
      ),
    ),
  );
}
