name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Download Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Copy google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo "$GOOGLE_SERVICES" > android/app/google-services.json

      - name: Copy firebase_options.dart
        env:
          DART_FIREBASE_OPTIONS: ${{ secrets.DART_FIREBASE_OPTIONS }}
        run: echo "$DART_FIREBASE_OPTIONS" > lib/firebase_options.dart

      - name: Get dependencies
        run: flutter pub get

      - name: Build for Web
        run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VEHIKL_SPARE_PARTS }}'
          channelId: live
          projectId: vehikl-spare-parts
